### ISSUE TITLE
Any suitable watershed algorithms that one can use for urban terrain with lots of flat area?

### ISSUE THREAD

**Issue by WindingWinter** [r-barnes/richdem#11]
My terrain is highly developed urban area, with a lot of paved development and flat surface, and platform with sudden drop ( think of retaining walls and drains).

Without knowing the specific characteristics of the urban area, I wonder whether is there any flow accumulation/watershed algorithms that are suitable?

**Comment by r-barnes** [comment]
@WindingWinter: The depression-filling algorithm has an [epsilon gradient](https://richdem.readthedocs.io/en/latest/depression_filling.html#epsilon-filling) option which can be used to ensure that flat surfaces drain.

You could also fill/breach depressions and then use a [flat resolver](https://richdem.readthedocs.io/en/latest/flat_resolution.html).

You will probably want to retain your original surface if you are doing iterative modeling since the above methods will modify the DEM.

Does this help?
