### ISSUE TITLE
Provide examples for C++ usage

### ISSUE THREAD

**Issue by WindingWinter** [r-barnes/richdem#9]
I notice that RichDEM is rich with python script example ( such as [this one](https://richdem.readthedocs.io/en/latest/example_dems.html)), but I don't see C++ calling.

I'm planning to call RichDEM from my C++ code, and as such, C++ sample would be useful. 

Thank you for your help!

More info: I'm running on Windows, Visual Studio 2015. So it would be great if you can provide the VS 2015 solution and csproject files on Github.

**Comment by r-barnes** [comment]
This is a weakness of the current documentation. However, the C++ functions you need should be listed in the documentation and more information about this functions can be found in the [C++ documentation](https://richdem.readthedocs.io/en/latest/cpp_api.html).

Look in the `richdem/apps` directory to find a number of example scripts using the C++ portions of the library.

It's unlikely that I will add specific support for Visual Studio or Windows, beyond working to ensure that the Python wrapper compiles on Windows. It's not an operating system I have regular access to. Since this is open source software, I'm happy to talk about ways in which you could contribute MSVC solutions.

Since the library is (nearly) header-only, I expect it shouldn't be too difficult to import into your environment.
